---
title: "tidytuesday_2019_week17"
author: "Youngseok Hahm"
date: "12/16/2019"
output: 
  html_document:
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Call library
```{r library_call, message=FALSE}
library(tidyverse)
library(gganimate)
library(plotly)
```


# Get the Data
```{r data_collection, message = FALSE}
dog_descriptions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-12-17/dog_descriptions.csv')
```

# Data Cleaning
```{r}
# 33 observations with wrong data entry
# data from column 26 ('photo') should be moved to right by one
temp = dog_descriptions %>% filter(status != 'adoptable')
head(temp[,25:28])
temp[, 27:34] = temp[, 26:33]
temp[,26] = NA
head(temp[,25:28])
# Update the original dataset
dog_descriptions[match( temp$url, dog_descriptions$url ), ] <- temp
```

```{r, collapse=TRUE}
dog_descriptions %>% 
  group_by(contact_state) %>%
  summarize(total = n()) %>%
  top_n(20, total) %>%
  select(contact_state) -> top_20_states
# Top 20 states with most adoptable dogs available by sex
dog_descriptions %>%
  filter(contact_state %in% top_20_states$contact_state ) %>%
  group_by(contact_state, sex) %>%
  summarize(count = n()) %>%
  plot_ly(x = ~contact_state, y = ~count, type = "bar", color = ~sex) %>%
  layout(
    title = "Top 20 states with most adoptable dogs available by sex",
    xaxis = list( title = "State abbreviation"),
    yaxis = list( title = "Number of adoptable dogs")
  )
    
# Top 20 states with most adoptable dogs available by age
dog_descriptions %>%
  filter(contact_state %in% top_20_states$contact_state ) %>%
  group_by(contact_state, age) %>%
  summarize(count = n()) %>%
  plot_ly(x = ~contact_state, y = ~count, type = "bar", color = ~age) %>%
  layout(
    title = "Top 20 states with most adoptable dogs available by age",
    xaxis = list( title = "State abbreviation"),
    yaxis = list( title = "Number of adoptable dogs")
  )
```


```{r, collapse=TRUE}
scale_graph = function(x) {
  (x - min(x))/(max(x)-min(x))
}
dog_descriptions %>%
  mutate( posted_date = str_extract(posted, "([^T]+)") ) %>%
  select(posted_date) %>%
  group_by(posted_date) %>%
  summarize(count = n()) %>%
  mutate( year = strsplit(posted_date, '-') %>% map_chr(., 1),
          month = months(as.Date(posted_date)),
          count = scale_graph(count)) %>%
  filter( year == '2019' ) -> data_visualization
data_visualization %>%
  group_by(month) %>%
  summarize(start=min(posted_date), end=max(posted_date)) %>%
  rowwise() %>%
  mutate(month_label = months(as.Date(start)),
         mid_point = as.character( as.Date(start) + floor((as.Date(end) - as.Date(start))/2))) -> data_label
p <- ggplot(data = data_visualization, aes(x = posted_date, y = count, fill=month )) + 
  geom_bar(stat="identity", alpha = 0.5) +
  ylim(-0.5,1) +
  theme_minimal() +
  theme(
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
  ) +
  coord_polar(start = 0) +
  geom_text(data = data_label, aes(x = mid_point, y = -0.1, label = month_label), colour = "black", alpha=0.8, size=1.4, inherit.aes = FALSE) 
p + labs(title = "Adoptable dogs posted by month in 2019 (scaled)")
```